# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: flutter1999
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bannerService

provider:
  name: aws
  runtime: nodejs20.x
  region: "eu-north-1"
  environment:
    DYNAMODB_TABLE: "Banners"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::banner-images-aptechclass-1999/*

    
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:eu-north-1:717279726910:table/Banners



resources:
  Resources:
    BannerImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-aptechclass-1999
  
    BannersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Banners
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH


functions:
  hello:
    handler: handler.getSignedUrl
    events:
      - httpApi:
          path: /get-upload-url
          method: post
  getAllBanners:
    handler: getAllBanners.getAllBanners
    events:
      - httpApi:
          path: /get-upload-url
          method: get

  confirmUpload:
    handler: confirmUpload.confirmUpload
    events:
      - s3:
          bucket: banner-images-aptechclass-1999
          event: s3:ObjectCreated:Put

          existing: true
